general {
    monitor =
    hide_cursor = true
    immediate_render = true
}

auth {
    pam:enabled = true
}

animations {

}


background {
    monitor =
    path = screenshot
    color = rgba(ffffff00)
    blur_passes = 3
    blur_size = 7
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 1

    inner_color = rgba(282828ff) # no fill
    outer_color = rgba(8ec07cff) rgba(8ec07cff) 45deg
    check_color = rgba(8ec07cff) rgba(8ec07cff) 120deg
    fail_color = rgba(cc241dff) rgba(cc241dff) 40deg

    font_color = rgba(ebdbb2ff)
    fade_on_empty = false
    rounding = 3
    placeholder_text = <i>Password</i>
    capslock_color = rgba(fabd2fff)
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    text_align = center
    color = rgba(ebdbb2ff)
    font_size = 50
    position = 0, 80
    halign = center
    valign = center
    
}
