background		= rgba(1d2021ff) # Background color.
base			= rgba(282828ff) # Base color.
text			= rgba(ebdbb2ff) # Text color.
alternate_base		= rgba(3c3836ff) # Alternative base color.
bright_text		= rgba(fbf1c7ff) # Bright text color.
accent			= rgba(8ec08cff) # Accent color.
accent_secondary	= rgba(d3869bff) # Secondary accent color.
h1_size			= 19		 # Font size for H1.
h2_size			= 15		 # Font size for H2.
h3_size			= 13		 # Font size for H3.
font_size		= 11		 # Font size for regular text elements.
small_font_size		= 10		 # Font size for small text elements.
icon_theme		= empty		 # Name of the icon theme to use, empty for “the first found”.
font_family		= Sans Serif	 # Name of the font family to use.
font_family_monospace	= monospace	 # Name of the monospace font family to use.
rounding_large		= 3		 # Big rounding in logical px
rounding_small		= 3		 # Small rounding in logical px